os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode10.1
services: docker

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      SWIFT_VERSION=$(<.swift-version);
      docker pull swift:${SWIFT_VERSION};
    elif [ $TRAVIS_OS_NAME == "osx" ]; then
      rvm use 2.5.1 --install --binary --fuzzy;
      ruby --version;
      gem install bundler;
      bundle --version;
      brew update;
      brew outdated swiftlint || brew upgrade swiftlint;
    fi

install:
  - if [ $TRAVIS_OS_NAME == "osx" ]; then
      bundle install --jobs=3 --retry=3 --deployment;
    fi

script:
  - if [ $TRAVIS_OS_NAME == "osx" ]; then
      swift --version;
      swift build;
      swift build -c release;
      swift test;
      swiftlint;
    else
      docker run --rm -v $(pwd):/app --workdir /app swift:${SWIFT_VERSION} bash -c "swift build && swift build -c release && swift test";
    fi

notifications:
  email:
    on_success: never
    on_failure: change
