language: generic

before_install:
  - export SWIFT_VERSION=$(<.swift-version)
  - export SWIFT_DOCKER_IMAGE=swift:${SWIFT_VERSION}-bionic
  - export MONGO_DOCKER_IMAGE=mongo:4.0.12
  - export MONGO_BREW_VERSION=mongodb-community@4.0
  - export MONGO_C_DRIVER=1.15.1

stages:
- name: test
  if: tag IS NOT present

jobs:
  include:

    - stage: test
      name: Unit Tests
      os: linux
      dist: bionic
      services: docker
      script:
        - docker pull ${SWIFT_DOCKER_IMAGE}
        - docker pull ${MONGO_DOCKER_IMAGE}
        - docker run -d -p 27017:27017 ${MONGO_DOCKER_IMAGE}
        - args="apt-get update
            && apt-get -y install wget cmake libssl-dev libsasl2-dev
            && wget https://github.com/mongodb/mongo-c-driver/releases/download/${MONGO_C_DRIVER}/mongo-c-driver-${MONGO_C_DRIVER}.tar.gz
            && tar xzf mongo-c-driver-${MONGO_C_DRIVER}.tar.gz
            && pushd mongo-c-driver-${MONGO_C_DRIVER}
            && cmake -DENABLE_AUTOMATIC_INIT_AND_CLEANUP=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr
            && make install
            && popd
            && swift build -c debug
            && swift build -c release
            && swift test -c debug --sanitize=thread --enable-test-discovery";        
        - docker run --rm --net=host -v $(pwd):/app --workdir /app ${SWIFT_DOCKER_IMAGE} bash -c "${args}"

    - stage: test
      name: Unit Tests
      os: osx
      osx_image: xcode11
      before_script:
        - gem install bundler
        - bundle install
        - brew update
        - brew tap mongodb/brew
        - brew install ${MONGO_BREW_VERSION}
        - brew services start ${MONGO_BREW_VERSION}
        - brew install mongo-c-driver
        - brew outdated swiftlint || brew upgrade swiftlint
      script:
        - swift --version
        - swift build
        - swift build -c release
        - swift test
        - swiftlint

notifications:
  email:
    on_success: never
    on_failure: change
