language: generic

before_install:
  - export SWIFT_VERSION=$(<.swift-version)
  - export SWIFT_DOCKER_IMAGE=swift:${SWIFT_VERSION}-bionic
  - export MONGO_DOCKER_IMAGE=mongo:4.0.12

stages:
- name: test
  if: tag IS NOT present

jobs:
  include:

    - stage: test
      name: Unit Tests
      os: linux
      dist: bionic
      services: docker
      script:
        - docker pull ${SWIFT_DOCKER_IMAGE}
        - docker pull ${MONGO_DOCKER_IMAGE}
        - docker run -d -p 27017:27017 ${MONGO_DOCKER_IMAGE}
        - args="apt-get update
            && apt-get -y install cmake
            && git clone -b r1.14 https://github.com/mongodb/mongo-c-driver /tmp/libmongoc
            && pushd /tmp/libmongoc
            && cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr
            && make -j8 install
            && popd
            && swift build -c debug
            && swift build -c release
            && swift test -c debug --sanitize=thread --enable-test-discovery";        
        - docker run --rm --net=host -v $(pwd):/app --workdir /app ${SWIFT_DOCKER_IMAGE} bash -c "${args}"

    - stage: test
      name: Unit Tests
      os: osx
      osx_image: xcode11
      before_script:
        - gem install bundler
        - bundle install
        - brew update
        - brew install mongo-c-driver
        - brew install mongodb
        - brew outdated swiftlint || brew upgrade swiftlint
        - brew services start mongodb
      script:
        - swift --version
        - swift build
        - swift build -c release
        - swift test
        - swiftlint

notifications:
  email:
    on_success: never
    on_failure: change
