os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode10.1
services: docker

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      SWIFT_VERSION=$(<.swift-version);
      docker pull swift:${SWIFT_VERSION};
      docker pull mongo:3.6.8;
      docker run -d -p 27017:27017 mongo:3.6.8;
    elif [ $TRAVIS_OS_NAME == "osx" ]; then
      rvm use 2.5.1 --install --binary --fuzzy;
      ruby --version;
      gem install bundler;
      bundle --version;
      brew update;
      brew install mongo-c-driver;
      brew install mongodb;
      brew services start mongodb;
      brew outdated swiftlint || brew upgrade swiftlint;
    fi

install:
  - if [ $TRAVIS_OS_NAME == "osx" ]; then
      bundle install --jobs=3 --retry=3 --deployment;
    fi

script:
  - if [ $TRAVIS_OS_NAME == "osx" ]; then
      swift --version;
      swift build;
      swift build -c release;
      swift test;
      swiftlint;
    else
      args="wget https://github.com/mongodb/mongo-c-driver/releases/download/1.13.0/mongo-c-driver-1.13.0.tar.gz \
        && tar xzf mongo-c-driver-1.13.0.tar.gz \
        && cd mongo-c-driver-1.13.0 \
        && mkdir cmake-build \
        && cd cmake-build \
        && cmake -DENABLE_AUTOMATIC_INIT_AND_CLEANUP=OFF \
        && swift build \
        && swift build -c release && \
        swift test"
      docker run --rm -v $(pwd):/app --workdir /app swift:${SWIFT_VERSION} bash -c ${args};
    fi

notifications:
  email:
    on_success: never
    on_failure: change
