version: "3"
services:

  mongo-setup:
    image: mongo:7
    restart: on-failure
    volumes:
      - ./Scripts:/scripts
    entrypoint: [ "/scripts/mongo_setup.sh" ] # Make sure this file exists (see below for the setup.sh)
    depends_on:
      - node0
      - node1
      - node2
  
  node0:
    image: mongo:7
    container_name: node0
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    ports:
      - 27017:27017
  
  node1:
    image: mongo:7
    container_name: node1
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    ports:
      - 27018:27017

  node2:
    image: mongo:7
    container_name: node2
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
    ports:
      - 27019:27017
