version: "3"
services:

  mongo-setup:
    image: mongo:7
    restart: on-failure
    network_mode: host
    volumes:
      - ./Scripts:/scripts
    entrypoint: [ "/scripts/mongo_setup.sh" ] # Make sure this file exists (see below for the setup.sh)
    depends_on:
      - node0
      - node1
      - node2
  
  node0:
    image: mongo:7
    restart: always
    network_mode: host
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--port", "27017" ]
    expose:
      - 27017
  
  node1:
    image: mongo:7
    restart: always
    network_mode: host
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--port", "27018" ]
    expose:
      - 27018

  node2:
    image: mongo:7
    restart: always
    network_mode: host
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0", "--port", "27019" ]
    expose:
      - 27019
